name: RCP_LO
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - attrs==25.1.0
      - backcall==0.2.0
      - blinker==1.8.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.2.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - fonttools==4.56.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - intel-cmplr-lib-ur==2025.0.5
      - intel-openmp==2025.0.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiss-icp==1.2.3
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mkl==2025.0.1
      - mkl-service==2.4.0
      - narwhals==1.29.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==1.24.4
      - open3d==0.18.0
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.0.0
      - ply==3.11
      - pointnet2==0.0.0
      - prompt-toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rich==14.1.0
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shellingham==1.5.4
      - six==1.17.0
      - stack-data==0.6.3
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.16.0
      - typing-extensions==4.13.2
      - tzdata==2025.1
      - umf==0.9.1
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - zipp==3.20.2
