gpu: "0"
multi_gpu: null
eval_before: 0

model_name: model_rcplo

batch_size: 4
val_batch_size: 1  # eval
epochs: 299
learning_rate: 0.001

optimizer: AdamW
pretrain: null

weight_decay: 0.0001
dim: 3
num_points: 8192

DEVICE: cuda
evaluate: False

dataset: KITTI
val_dataset: KITTI
data_root: ./KITTI/sequences
val_path: ./KITTI/sequences

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

workers: 8






